Repository Ensembl/ensembl-datacheck, pull requests merged in 2019-09, with the labels that each got.

#127 Ported the UnreviewedXrefs hc to make sure UniProt Xrefs do not have …
  lib/Bio/EnsEMBL/DataCheck/Checks/UnreviewedXrefs.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#130 Ported the XrefHTML hc. Fixed the regex as the original code was chec…
  lib/Bio/EnsEMBL/DataCheck/Checks/XrefHTMLBlank.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#131 Ported the DuplicateXref Hc which also support part of the retired Du…
  lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateXref.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#133 Stable id display xref
  lib/Bio/EnsEMBL/DataCheck/Checks/StableIdDisplayXref.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#124 Porting ComparePreviousVersionGOXrefs healthcheck. This compare the G…
  lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGOXrefs.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#125 Converted HC to make sure that all the GO xrefs have an evidence
  lib/Bio/EnsEMBL/DataCheck/Checks/GOXrefEvidence.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#135 Porting the TranscriptDisplayXrefSuffix HC. This only apply to non-ve…
  lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptDisplayXrefSuffix.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#128 Ported the XrefPrefixes HC which checks that GO, MGI and ZFIN dbprima…
  lib/Bio/EnsEMBL/DataCheck/Checks/XrefPrefixes.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#134 Converted HC to check if species inside a collection have protein cod…
  lib/Bio/EnsEMBL/DataCheck/Checks/SharedDisplayXref.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#136 Ported XrefDescriptionSpecialChars, since we have a DC already doing …
  lib/Bio/EnsEMBL/DataCheck/Checks/XrefFormat.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#137 Sundry updates and fixes
  lib/Bio/EnsEMBL/DataCheck/Checks/ChromosomesAnnotated.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyAssembly.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm
  lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSummary.pm
  lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
Labels: enhancement

#140 Ported ComparePreviousVersionProjectedGeneNames HC. The original hc w
  lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGeneNames.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#138 Ported the UniProtKB_DisplayXrefIds HC. Extended the check to include…
  lib/Bio/EnsEMBL/DataCheck/Checks/UniProtDisplayXref.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#141 Ported SimpleFeatureAnalysisTypes HC which make sure simple_features …
  lib/Bio/EnsEMBL/DataCheck/Checks/SimpleFeatureAnalysisTypes.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#143 New translation/protein feature checks
  lib/Bio/EnsEMBL/DataCheck/Checks/ProteinFeatureLength.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ProteinFeatures.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ValidTranslations.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement

#144 Update CompareSchema datacheck
  lib/Bio/EnsEMBL/DataCheck/Checks/CompareSchema.pm
  lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
Labels: enhancement

#147 Porting the TranscriptSameName hc. This check make sure that Protein …
  lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateTranscriptNames.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#146 Porting the TranscriptSameName hc. This check make sure that Protein …
  lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateTranscriptNames.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: feature

#150 Variation schema changed after we had updated test dbs
  t/test-genome-DBs/homo_sapiens/variation/meta.txt
  t/test-genome-DBs/homo_sapiens/variation/table.sql
Labels: bug

#152 Configure travis to use release version branches…
  .travis.yml
Labels: enhancement

#153 Fix for embedded datacheck output
  lib/Bio/EnsEMBL/DataCheck/Pipeline/Example_conf.pm
  lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm
Labels: bug

#154 New module to send an email for a failed Datcheck with datacheck name…
  lib/Bio/EnsEMBL/DataCheck/Pipeline/EmailNotify.pm
Labels: feature
