Repository Ensembl/ensembl-datacheck, pull requests merged in 2020-06, with the labels that each got.

#253 Adding group for compara ancestral databases.
  lib/Bio/EnsEMBL/DataCheck/Checks/AnalysisFormat.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/AssemblyExceptions.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/AssemblySeqregion.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/BlankEnums.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/DatabaseCollation.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyCardinality.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyLevel.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SchemaVersion.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionNames.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
  scripts/run_datachecks.pl
Labels: feature

#257 New datacheck to ensure correct display of NCBI gene and transcript accessions
  lib/Bio/EnsEMBL/DataCheck/Checks/NCBIGeneLabels.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement

#263 Fix typo in method name
  lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm
Labels: bug

#264 Remove skeleton datachecks for unimplemented functionality.
  lib/Bio/EnsEMBL/DataCheck/Checks/DNAFragCore.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/GenomeDBCore.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: bug

#262 Brc4 fixes
  lib/Bio/EnsEMBL/DataCheck/Checks/ControlledAnalysisVersion.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MTCodonTable.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyBRC4.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionBRC4.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesTaxonomy.pm
Labels: enhancement

#265 remove known phenotype descriptions
  lib/Bio/EnsEMBL/DataCheck/Checks/PhenotypeDescription.pm
Labels: enhancement

#261 RNA-seq daf analyses and features checks.
  lib/Bio/EnsEMBL/DataCheck/Checks/RNASeqDNAAlignFeatureAnalyses.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement
