Repository Ensembl/ensembl-datacheck, pull requests merged in 2020-01, with the labels that each got.

#178 Foreign Key datacheck for compara
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyLevel.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement

#179 Some vertebrate species need more memory
  lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
Labels: enhancement

#172 Test to check stable id mapping between two releases
  lib/Bio/EnsEMBL/DataCheck/Checks/CompareStableIdsMapping.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement

#181 Miscellaneous small bugfixes
  lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCore.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ExonBounds.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm
  lib/Bio/EnsEMBL/DataCheck/Manager.pm
  lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
Labels: bug

#183 Add Test::JSON to cpanfile
  cpanfile
Labels: feature

#185 Removed harcoded list of species for APPRIS since we will plug this D…
  lib/Bio/EnsEMBL/DataCheck/Checks/AttribValues.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/AttribValuesCoverage.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/AttribValuesExist.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement

#184 Adaptive_memeory: New job added RunDataChecks_High_mem and DataCheckF…
  lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
Labels: enhancement
