Repository Ensembl/ensembl-datacheck, pull requests merged in 2020-05, with the labels that each got.

#239 pipeline name added in emailnotify subject
  lib/Bio/EnsEMBL/DataCheck/Pipeline/EmailNotify.pm
Labels: feature

#238 Update VersionedGenes.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm
Labels: bug

#244 Adding test for the presence of a motif_feature file.
  lib/Bio/EnsEMBL/DataCheck/Checks/DataFilesExist.pm
Labels: bug

#245 Force datachecks that rely on multiple databases to always be run...
  lib/Bio/EnsEMBL/DataCheck/Checks/CoreTables.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/FeaturePosition.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysMultiDB.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaCoord.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConsistent.pm
Labels: bug

#246 Updating Denormalized and MultipleSeqRegions
  lib/Bio/EnsEMBL/DataCheck/Checks/Denormalized.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MultipleSeqRegions.pm
Labels: bug

#247 Determine old version of compara and ontology databases
  lib/Bio/EnsEMBL/DataCheck/Checks/CompareOntologyTerm.pm
  lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
  scripts/run_datachecks.pl
Labels: bug

#249 Update datachecks related to GO xrefs
  lib/Bio/EnsEMBL/DataCheck/Checks/GOXrefEvidence.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/XrefTypes.pm
Labels: bug

#251 New compara datachecks
  lib/Bio/EnsEMBL/DataCheck/Checks/DNAFragCore.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/GeneTreeHighlighting.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/GenomeDBCore.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagGERP.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagHomology.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagMaxAlign.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagMultipleAlignment.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagPairwiseAlignment.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagSynteny.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagThresholdDs.pm
  lib/Bio/EnsEMBL/DataCheck/Test/Compara.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement
