Repository Ensembl/ensembl-datacheck, pull requests merged in 2021-03, with the labels that each got.

#349 hot_fix/repeatdetector_metakey
  lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm
Labels: bug

#351 New Compara Groups for RR
  lib/Bio/EnsEMBL/DataCheck/Checks/BlankEnums.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckDuplicatedTaxaNames.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckReleaseConsistency.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckReleaseNulls.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckSequenceTable.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesSetTable.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/CigarCheck.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SchemaPatchesApplied.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SchemaType.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SchemaVersion.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement, feature

#352 Extend advisory phenotype description DC to report specific descriptions
  lib/Bio/EnsEMBL/DataCheck/Checks/PhenotypeDescription.pm
Labels: enhancement, feature

#354 Bugfix incorrectly expressed regular expression
  lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
Labels: bug

#353 New DC group "long_running_dc" for Denormalized.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/Denormalized.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
Labels: enhancement

#357 Fix for PlastidsAnnotated datacheck
  lib/Bio/EnsEMBL/DataCheck/Checks/PlastidsAnnotated.pm
Labels: bug
