Repository Ensembl/ensembl-datacheck, pull requests merged in 2021-10, with the labels that each got.

#416 Feature/collective advisory dc report
  lib/Bio/EnsEMBL/DataCheck/Pipeline/AdvisoryDataCheckSummary.pm
Labels: feature

#413 Updating test dbs to latest schema
  t/test-genome-DBs/collection/core/meta.txt
  t/test-genome-DBs/collection/core/table.sql
  t/test-genome-DBs/drosophila_melanogaster/core/meta.txt
  t/test-genome-DBs/drosophila_melanogaster/core/table.sql
  t/test-genome-DBs/homo_sapiens/core/meta.txt
  t/test-genome-DBs/homo_sapiens/core/table.sql
  t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
  t/test-genome-DBs/homo_sapiens/funcgen/table.sql
  t/test-genome-DBs/homo_sapiens/variation/meta.txt
  t/test-genome-DBs/homo_sapiens/variation/table.sql
  t/test-genome-DBs/multi/compara/meta.txt
  t/test-genome-DBs/multi/compara/table.sql
Labels: bau

#417 New required transcript attrib for all canonical transcript
  lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptSupport.pm
Labels: enhancement
