Repository Ensembl/ensembl-datacheck, pull requests merged in 2022-01, with the labels that each got.

#430 Release/106
  .travis.yml
  lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateComparaMemberXref.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesCommonName.pm
  lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptSupport.pm
  lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
  lib/Bio/EnsEMBL/DataCheck/index.json
  t/DbCheck_noncore.t
  t/test-genome-DBs/multi/compara/meta.txt
  travisci/harness.sh
Labels: bau

#437 Use git ensembl to clone repos.
  .travis.yml
  travisci/harness.sh
Labels: bug, enhancement

#435 Allow for _ to be part of the display name format.
  lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm
Labels: enhancement

#436 Allow for _ to be part of the display name format.
  lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm
Labels: enhancement

#439 Update DisplayNameFormat.pm -- use "," (release/105)
  lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm
Labels: enhancement, bau

#442 DisplayNameFormat support for "." and "#" (105)
  lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm
Labels: enhancement

#444 DisplayNameFormat support for ",.#_" (106)
  lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm
Labels: enhancement

#443 DisplayNameFormat support for "." and "#" (107)
  lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm
Labels: enhancement

#446 Bugfix/compara species url
  lib/Bio/EnsEMBL/DataCheck/Checks/MartDatasetName.pm
Labels: bug

#448 Fixed cmp_ok error when '=' ==> '=='
  lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptSupport.pm
Labels: bug

#449 Fixed cmp_ok error when '=' ==> '=='
  lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptSupport.pm
Labels: bug

#451 Added protein_coding_LoF as an allowed biotype for canonical transcri…
  lib/Bio/EnsEMBL/DataCheck/Checks/CanonicalTranscripts.pm
Labels: enhancement

#452 Division name included in subtest header
  lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
  t/DbCheck.t
Labels: enhancement

#458 Fixed typo in Text for Advisory DC report
  lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckMailSummary.pm
Labels: bug
